### ISSUE TITLE
Input must be manually blurred to clear async error

### ISSUE THREAD

**Issue by therealklanni** [kogosoftwarellc/angular-async-form#3]
### Problem
If an input is hidden and used to collect a computed value from another input(s), an async form error associated with the hidden input does not clear automatically when its value is updated (blur must be triggered manually).

In my opinion, inputs validated by async form should only show the error based on `$valid`/`$invalid` state of the model, thus not requiring blur/change events.

### Scenario

```js
function link(scope, el) {
  scope.$watch('input1', function(value) {
    $timeout(function() {
      scope.$apply(function() {
        input2.$setViewValue(value)
        // if async error exists, error will not be hidden
        // despite this model being $valid
      })
    }, 0, false)
  })
```

### Workaround

```js
function link(scope, el) {
  var input2el

  $timeout(function() {
    input2el = angular.element(el.find('input2'))
  })

  scope.$watch('input1', function(value) {
    $timeout(function() {
      scope.$apply(function() {
        input2.$setViewValue(value)
        input2el.triggerHandler('blur')
        // async error will now get cleared
      })
    }, 0, false)
  })
```

**Comment by therealklanni** [comment]
### Potential Fix

On [L240](https://github.com/kogosoftwarellc/angular-async-form/blob/master/lib/angular-async-form.js#L240) you might be better off with 

```js
scope.$watch(name, function() {
  // check ngModel.$valid here and call controlGroup.hideError()
})
```

**Comment by jsdevel** [comment]
> In my opinion, inputs validated by async form should only show the error based on $valid/$invalid state of the model, thus not requiring blur/change events.

Is it necessary to use `af-control` with the hidden input?  Doesn't seem like it should be.  The whole point of `af-control` is to display a message from the backend validation to the user so they can fix what their input was.  In the case of a hidden input, there's nothing the user can do.

**Comment by therealklanni** [comment]
As mentioned, the hidden input is collecting a computed value from one or more user-controlled inputs.

**Comment by jsdevel** [comment]
> As mentioned, the hidden input is collecting a computed value from one or more user-controlled inputs.

I understand that.

I would suggest removing `af-control` from the hidden input entirely.  If you need to show a message for the input that makes up part of the computed value, then add a custom `handleSubmit` function that renames the error key from the name of the hidden input to the user facing one.
